language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
install: ./composer install
script: scripts/run_full_tests.sh
before_script: mysql -e 'create database hades_test; grant all on hades_test.* to hades@localhost identified by "hades";' -uroot